### ISSUE TITLE
Traceback at cmdline in shiny

### ISSUE THREAD

**Issue by jeanconn** [sot/testr#33]
I'm getting this 
```
Traceback (most recent call last):
  File "/proj/sot/ska3/shiny/bin/run_testr", line 33, in <module>
    sys.exit(load_entry_point('testr==4.5.0', 'console_scripts', 'run_testr')())
  File "/proj/sot/ska3/shiny/lib/python3.8/site-packages/testr/packages.py", line 665, in main
    write_log(tests)
  File "/proj/sot/ska3/shiny/lib/python3.8/site-packages/testr/packages.py", line 463, in write_log
    test_suites['run_info']['t_stop'] = min([ts['properties']['t_stop']
  File "/proj/sot/ska3/shiny/lib/python3.8/site-packages/testr/packages.py", line 465, in <listcomp>
    ts['properties']['t_start'] is not None])
TypeError: 'NoneType' object is not subscriptable
```

That was on my latest run of `run_testr --include cxotime`.  I haven't run a spec yet.

**Comment by jeanconn** [comment]
Nevermind.  I guess there was something in my ska_testr repo that was dirty enough to make this unhappy.  I cleaned the repo and the traceback went away.
